create table DEPARTMENTS
(
	CODE VARCHAR(10) not null primary key,
	NAME VARCHAR(30) not null,
	FACULTY_CODE VARCHAR(5) not null,
	CHAIR_ID INTEGER
);

create table INSTRUCTORS
(
	ID INTEGER not null primary key,
	NAME VARCHAR(30) not null,
	SURNAME VARCHAR(30),
	DEPARTMENT_CODE VARCHAR(10) not null references DEPARTMENTS
);

alter table DEPARTMENTS
	add foreign key (CHAIR_ID) references INSTRUCTORS;

create table STUDENTS
(
	ID INTEGER not null primary key,
	NAME VARCHAR(30) not null,
	SURNAME VARCHAR(30) not null,
	DEPARTMENT_CODE VARCHAR(10) not null references DEPARTMENTS,
	EMAIL VARCHAR(50) unique
);

INSERT INTO DEPARTMENTS (CODE, NAME, FACULTY_CODE, CHAIR_ID) VALUES ('CS', 'Computer Science', 'ENG', null);
INSERT INTO DEPARTMENTS (CODE, NAME, FACULTY_CODE, CHAIR_ID) VALUES ('MATH', 'Mathematics', 'NS', null);
INSERT INTO DEPARTMENTS (CODE, NAME, FACULTY_CODE, CHAIR_ID) VALUES ('EC', 'Economics', 'MGMT', null);
INSERT INTO DEPARTMENTS (CODE, NAME, FACULTY_CODE, CHAIR_ID) VALUES ('EE', 'Eletronic Engineering', 'ENG', null);
INSERT INTO DEPARTMENTS (CODE, NAME, FACULTY_CODE, CHAIR_ID) VALUES ('PHYS', 'Physics', 'NS', null);
INSERT INTO DEPARTMENTS (CODE, NAME, FACULTY_CODE, CHAIR_ID) VALUES ('ENG', 'English', 'LIT', null);
INSERT INTO DEPARTMENTS (CODE, NAME, FACULTY_CODE, CHAIR_ID) VALUES ('PHIL', 'Philosophy', 'SS', null);

INSERT INTO STUDENTS (ID, NAME, SURNAME, DEPARTMENT_CODE, EMAIL) VALUES (1, 'Franz', 'Kafka', 'CS', 'fkafka@unyt.edu.al');
INSERT INTO STUDENTS (ID, NAME, SURNAME, DEPARTMENT_CODE, EMAIL) VALUES (2, 'Thomas', 'Mann', 'CS', 'tmann@unyt.edu.al');
INSERT INTO STUDENTS (ID, NAME, SURNAME, DEPARTMENT_CODE, EMAIL) VALUES (3, 'Elfriede', 'Jelinek', 'MATH', 'ejelinek@unyt.edu.al');
INSERT INTO STUDENTS (ID, NAME, SURNAME, DEPARTMENT_CODE, EMAIL) VALUES (4, 'Günther', 'Grass', 'EE', 'ggrass@unyt.edu.al');
INSERT INTO STUDENTS (ID, NAME, SURNAME, DEPARTMENT_CODE, EMAIL) VALUES (5, 'Stephan', 'Zweig', 'MATH', 'szweig@unyt.edu.al');

INSERT INTO INSTRUCTORS (ID, NAME, SURNAME, DEPARTMENT_CODE) VALUES (1, 'Alan', 'Turing', 'CS');
INSERT INTO INSTRUCTORS (ID, NAME, SURNAME, DEPARTMENT_CODE) VALUES (2, 'Marvin', 'Minsky', 'CS');
INSERT INTO INSTRUCTORS (ID, NAME, SURNAME, DEPARTMENT_CODE) VALUES (3, 'Claude', 'Shannon', 'EE');
INSERT INTO INSTRUCTORS (ID, NAME, SURNAME, DEPARTMENT_CODE) VALUES (4, 'Joshua', 'Bengio', 'CS');

UPDATE DEPARTMENTS SET CHAIR_ID = 1 WHEE CODE = 'CS';
